server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:55432/taskmanagement
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: taskmanagement

mizarion:
  jwt:
    secret: 6AF90C300504AB6601AB24E191603B304C804EA81AC0D6370A92A719B511FC2E6AF90C300504AB6601AB24E191603B30
    expiration: 86400
